image:
  repository: 514076760324.dkr.ecr.ap-south-1.amazonaws.com/cip-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP   # Changed from LoadBalancer
  port: 80

resources: {}

ingress:
  enabled: false

