apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testbitbucket78.fullname" . }}
  labels:
    app: {{ include "testbitbucket78.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "testbitbucket78.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "testbitbucket78.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: {{ include "testbitbucket78.fullname" . }}-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "testbitbucket78.fullname" . }}-html
data:
  index.html: |
    <html>
    <head><title>Test App</title></head>
    <body>
      <h1>Hello from Helm + Jenkins + EKS!</h1>
    </body>
    </html>

